name: build-release

on:
  release:
    types: [published]

jobs:
  test_faker_2_12:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Prepare maven
        env:
          MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$MVN_SETTINGS" | base64 -d > "$HOME"/.m2/settings.xml
          echo "$GPG_KEY" | base64 -d | gpg --import --batch > /dev/null 2>&1

      - name: Test
        run: mvn -ntp -B clean:clean test

      - name: Deploy faker_2.12
        run: mvn -ntp -B clean deploy -DskipTests -Prelease


  test_faker_2_11:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set scala 2.11
        run: |
          chmod +x ./dev/change-scala-version.sh
          ./dev/change-scala-version.sh 2.11

      - name: Prepare maven
        env:
          MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$MVN_SETTINGS" | base64 -d > "$HOME"/.m2/settings.xml
          echo "$GPG_KEY" | base64 -d | gpg --import --batch > /dev/null 2>&1

      - name: Test
        run: mvn -ntp -B clean:clean test

      - name: Deploy faker_2.11
        run: mvn -ntp -B clean deploy -DskipTests -Prelease