name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  test_faker_2_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        run: |
          mvn -ntp -B clean:clean scoverage:report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: pr
          name: codecov-pull-request

  test_faker_2_11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set scala 2.11
        run: |
          chmod +x ./dev/change-scala-version.sh
          ./dev/change-scala-version.sh 2.11

      - name: Run tests
        run: |
          mvn -ntp -B clean:clean scoverage:report
